package mchorse.bbs_mod.ui.supporters;

import mchorse.bbs_mod.resources.Link;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.stream.Collectors;

public class Supporters
{
    private List<Supporter> supporters = new ArrayList<>();

    public void setup()
    {
        /* Afdian */
        this.add("76823999").withDate(2, 29);
        this.add("Silly_Sheep_").withDate(2, 29);
        this.add("毫无人性的大麦纸", "https://space.bilibili.com/591074", "textures/banners/maizhi.png").withDate(2, 29);
        this.add("Afica").withDate(2, 29);
        this.add("XiaoTu_MC", "https://v.douyin.com/iNwM4XEr/", "...").withDate(3, 1);
        this.add("白板弱者", "...").withDate(3, 1);
        this.add("Rainbow Stars").withDate(3, 1);
        this.add("开智同学").withDate(3, 2);
        this.add("Fight凡子").withDate(3, 2);
        this.add("零雾〇五Fogg05").withDate(3, 2);
        this.add("GODZILLA256", "https://space.bilibili.com/17798027", "textures/banners/godzilla256.png").withDate(3, 2);
        this.add("LiteCat").withDate(3, 2);
        this.add("一只蟠桃peach").withDate(3, 2);
        this.add("tianqo").withDate(3, 3);
        this.add("Tanis Gon").withDate(3, 3);
        this.add("ERroooooR", "https://space.bilibili.com/3546579457805118/").withDate(3, 3);
        this.add("澪L1ng", "https://space.bilibili.com/23839756", "textures/banners/l1ng.png").withDate(3, 3);
        this.add("爆风BooM", "https://space.bilibili.com/308180216").withDate(3, 3);
        this.add("Seven_Chad", "https://twitter.com/seven_chad", "textures/banners/seven_chad.png").withDate(3, 3);
        this.add("九纳森九斯达", "https://space.bilibili.com/17696710").withDate(3, 3);
        this.add("Deal").withDate(3, 3);
        this.add("凤天", "https://space.bilibili.com/22348510").withDate(3, 3);
        this.add("萱萱-3z", "https://space.bilibili.com/601994215", "textures/banners/xuanxuan.png").withDate(3, 3);
        this.add("白某人是个萌新", "...").withDate(3, 3);
        this.add("萌起MENGQI", "https://space.bilibili.com/2130239542", "textures/banners/mengqi.png").withDate(3, 3);
        this.add("Adfbulin", "https://space.bilibili.com/390313973").withDate(3, 3);
        this.add("方草块Minna").withDate(3, 3);
        this.add("Zhesheng_1818", "https://www.youtube.com/@MetalStorm_Studio").withDate(3, 3);
        this.add("暗影苦力怕 iter", "https://space.bilibili.com/472637101", "...").withDate(3, 3);
        this.add("ANDOG", "https://space.bilibili.com/25400883", "textures/banners/andog.png").withDate(3, 3);
        this.add("0tt0258").withDate(3, 3);
        this.add("NT_black", "https://space.bilibili.com/22190116").withDate(3, 3);
        this.add("iamli541").withDate(3, 3);
        this.add("望空希星", "https://space.bilibili.com/494577886", "...").withDate(3, 3);
        this.add("Relyonovo").withDate(3, 3);
        this.add("是老吴鸦").withDate(3, 3);
        this.add("一团糯米NuoMi").withDate(3, 3);
        this.add("第三位者").withDate(3, 3);
        this.add("星星会说话").withDate(3, 3);
        this.add("Foreboding萧").withDate(3, 3);
        this.add("篝火工作室").withDate(3, 3);
        this.add("star_tan").withDate(3, 3);
        this.add("绯色の白初").withDate(3, 3);
        this.add("GHL").withDate(3, 3);
        this.add("YuanMouRen").withDate(3, 3);
        this.add("冰糖梨丸").withDate(3, 3);
        this.add("LeaFire焰叶", "...").withDate(3, 3);
        this.add("超威乌龙喵", "https://space.bilibili.com/14359286").withDate(3, 3);
        this.add("稚名chclmii1", "https://space.bilibili.com/14359286").withDate(3, 3);
        this.add("星辰不是瓜").withDate(3, 4);
        this.add("暴碧Bobi").withDate(3, 4);
        this.add("WATERMELON").withDate(3, 4);
        this.add("无铭_Null").withDate(3, 4);
        this.add("silent", "https://space.bilibili.com/514637376").withDate(3, 4);
        this.add("Usaky舞麒", "https://space.bilibili.com/673732587", "textures/banners/usakywuqi.png").withDate(3, 4);
        this.add("流风LFloy", "...", "textures/banners/liufeng.png").withDate(3, 4);
        this.add("南风不知我意").withDate(3, 4);
        this.add("临夜Livie", "https://space.bilibili.com/1544935486").withDate(3, 5);
        this.add("小猪之最", "https://space.bilibili.com/381671770", "...").withDate(3, 6);
        this.add("宁儿", "...", "...").withDate(3, 7);
        this.add("Wenbai", "https://space.bilibili.com/697902619", "textures/banners/wenbai.png").withDate(3, 8);
        this.add("骚老师的MC动画").withDate(3, 9);
        this.add("Jackey_lin", "...").withDate(3, 9);
        this.add("HeimNad").withDate(3, 11);
        this.add("Minecraft地形师茶馆", "https://space.bilibili.com/3461578447915295").withDate(3, 12);
        this.add("Jmol", "https://space.bilibili.com/108360657").withDate(3, 13);
        this.add("Repeater", "...").withDate(3, 13);
        this.add("小博ace").withDate(3, 13);
        this.add("EliSATfe_").withDate(3, 13);
        this.add("百伽黎", "...").withDate(6, 11);
        this.add("愉悦的hehe11", "https://space.bilibili.com/3334737", "textures/banners/hehe11.png").withDate(3, 14);
        this.add("FenrirKK").withDate(3, 14);
        this.add("乐笑虾").withDate(3, 14);
        this.add("brisk_citrus凉柑").withDate(3, 14);
        this.add("娱儿游", "https://space.bilibili.com/42973624").withDate(3, 15);
        this.add("阿狐糊涂", "https://space.bilibili.com/3494374845450678").withDate(3, 15);
        this.add("渣暴风StorM", "https://space.bilibili.com/186424629").withDate(3, 15);
        this.add("瑭玟", "...", "...").withDate(3, 15);
        this.add("hao_yeah").withDate(3, 16);
        this.add("江枫珧").withDate(3, 16);
        this.add("安仙_9487").withDate(3, 16);
        this.add("碎梦入行", "https://space.bilibili.com/34789774").withDate(3, 16);
        this.add("益之冰棍", "https://space.bilibili.com/70170627").withDate(3, 16);
        this.add("Giftia", "https://space.bilibili.com/59624348", "...").withDate(3, 16);
        this.add("Yu_Feng").withDate(3, 16);
        this.add("洛筠sama", "https://space.bilibili.com/2035820829").withDate(3, 18);
        this.add("lkctrl").withDate(3, 18);
        this.add("飒爽师叔", "https://space.bilibili.com/22219285").withDate(3, 19);
        this.add("yeek").withDate(3, 20);
        this.add("mc47382").withDate(3, 20);
        this.add("浪濤", "https://space.bilibili.com/289923315", "textures/banners/langtao.png").withDate(3, 20);
        this.add("附魔粒子", "https://space.bilibili.com/45637223", "...").withDate(3, 22);
        this.add("涅泪", "https://space.bilibili.com/326657199", "textures/banners/nielei.png").withDate(3, 22);
        this.add("冰林L", "https://space.bilibili.com/497979931").withDate(3, 23);
        this.add("问学巨酱", "https://space.bilibili.com/635615190").withDate(3, 23);
        this.add("慕华lingzi").withDate(3, 23);
        this.add("靈音Nemloi").withDate(3, 23);
        this.add("风尘WD").withDate(3, 23);
        this.add("QingDame").withDate(3, 23);
        this.add("月影Yancie", "https://space.bilibili.com/3186399", "textures/banners/yancie.png").withDate(3, 24);
        this.add("凉茶是帅哥").withDate(3, 24);
        this.add("Ender_Moring UOP").withDate(3, 25);
        this.add("lighting").withDate(3, 25);
        this.add("扣肉", "https://space.bilibili.com/4868856").withDate(3, 25);
        this.add("ORDM 平凡的草民", "https://space.bilibili.com/87734289", "...").withDate(3, 25);
        this.add("纪夫Junly", "https://space.bilibili.com/19512037").withDate(3, 25);
        this.add("酷勒个白", "https://space.bilibili.com/41135516", "textures/banners/kuleigebai.png").withDate(3, 26);
        this.add("李开咕").withDate(3, 26);
        this.add("一千兆赫", "https://space.bilibili.com/1199808099").withDate(3, 26);
        this.add("穷思鸡", "https://space.bilibili.com/9661047", "...").withDate(3, 27);
        this.add("轩的游戏日志", "https://space.bilibili.com/175442023").withDate(3, 30);
        this.add("Saki_Rong").withDate(4, 2);
        this.add("zoombie").withDate(4, 3);
        this.add("Q").withDate(4, 5);
        this.add("ms影月").withDate(4, 6);
        this.add("夏月琳櫻").withDate(4, 6);
        this.add("四维灵动").withDate(4, 6);
        this.add("Msy默笙", "https://space.bilibili.com/284586643").withDate(4, 7);
        this.add("逢山栖影", "https://space.bilibili.com/453945116").withDate(4, 10);
        this.add("咕咕丸", "https://space.bilibili.com/46023616").withDate(4, 10);
        this.add("诺麟煌").withDate(4, 12);
        this.add("陈佬C", "https://space.bilibili.com/87026021", "textures/banners/chen_lao_c.png").withDate(4, 13);
        this.add("omo仙贝", "https://space.bilibili.com/1959304255", "textures/banners/omo.png").withDate(4, 16);
        this.add("叶落空留白").withDate(4, 18);
        this.add("银蝶餐饮工作室").withDate(4, 19);
        this.add("-叶落空留白-").withDate(4, 19);
        this.add("明光凯").withDate(4, 20);
        this.add("JzAa饺子", "https://space.bilibili.com/1048696948").withDate(4, 25);
        this.add("梓轩", "https://space.bilibili.com/1048696948").withDate(4, 25);
        this.add("我的世界萧鲲", "https://www.kuaishou.com/profile/3xxtz6m845v7pmg").withDate(4, 26);
        this.add("我的世界浴帽", "https://www.kuaishou.com/profile/3x3m75n5hat7wx2").withDate(4, 26);
        this.add("杨麒").withDate(4, 26);
        this.add("老鱿鱼").withDate(4, 26);
        this.add("HYN").withDate(4, 26);
        this.add("Fanconma").withDate(4, 27);
        this.add("夜洛伊ALOYI").withDate(4, 28);
        this.add("零子aqa").withDate(4, 29);
        this.add("戴特RinO").withDate(4, 30);
        this.add("Unsu1table").withDate(4, 30);
        this.add("幻灵吖phantom").withDate(5, 3);
        this.add("初夏少树").withDate(5, 5);
        this.add("韶光").withDate(5, 8);
        this.add("卷帘门金金爆", "https://space.bilibili.com/52665509").withDate(5, 9);
        this.add("千觞Ethan").withDate(5, 11);
        this.add("Lucas8989").withDate(5, 11);
        this.add("千年的启示").withDate(5, 11);
        this.add("酒辞").withDate(5, 11);
        this.add("块王c").withDate(5, 12);
        this.add("Turfore").withDate(5, 13);
        this.add("lxmgf").withDate(5, 14);
        this.add("Turmeric茶").withDate(5, 16);
        this.add("余生酱ovo").withDate(5, 16);
        this.add("华燃王小灭").withDate(5, 16);
        this.add("纽埃柯丝DEV").withDate(5, 18);
        this.add("FlipZack").withDate(5, 19);
        this.add("牧尘瑞斯muchenruisi", "https://v.kuaishou.com/Kqp32n").withDate(5, 19);
        this.add("YuSheng_ovo").withDate(5, 20);
        this.add("hulong").withDate(5, 24);
        this.add("大鱿鱼").withDate(5, 25);
        this.add("Not_vegetabledog").withDate(5, 29);
        this.add("节奏梦想").withDate(5, 31);
        this.add("ENDNULL", "https://space.bilibili.com/505118990", "textures/banners/ENDNULL.png").withDate(6, 3);
        this.add("布咕鸟不谷").withDate(6, 4);
        this.add("绚烂的白色").withDate(6, 6);
        // this.add("发电用户_yk").withDate(6, 7);
        this.add("dwqfafafs").withDate(6, 8);
        this.add("幽響の風穴").withDate(6, 9);
        this.add("子仁").withDate(6, 9);
        // this.add("爱发电用户_k9br").withDate(6, 9);
        this.add("克洛洛").withDate(6, 9);
        // this.add("爱发电用户_98497").withDate(6, 11);
        this.add("REL").withDate(6, 11);
        this.add("Sunwu_fang").withDate(6, 11);
        this.add("Jusyukin_BEE", "https://space.bilibili.com/86451726").withDate(6, 12);
        this.add("李炜").withDate(6, 13);
        this.add("诺子哥无法找到").withDate(6, 14);
        this.add("YLZA动画团队").withDate(6, 17);
        this.add("midnight").withDate(6, 17);
        this.add("咕咚").withDate(6, 18);
        this.add("喵不二本喵").withDate(6, 18);
        this.add("Bit3").withDate(6, 18);
        this.add("依潮水").withDate(6, 21);
        this.add("GoldenEggs").withDate(6, 22);
        this.add("QQ-oo~ee~oo").withDate(6, 23);
        this.add("一粒石头", "https://space.bilibili.com/279251784").withDate(6, 24);
        this.add("不在摸鱼之默栖").withDate(6, 25);
        this.add("aikesi X").withDate(6, 25);
        this.add("LabFie1d").withDate(6, 26);
        this.add("XINGCHNEG").withDate(6, 26);
        this.add("FanYe").withDate(6, 27);
        this.add("骑单车の茂茂").withDate(6, 27);
        this.add("Minecraft寒辰龙").withDate(6, 29);
        this.add("yuanyuanzhishui").withDate(6, 30);
        this.add("NirvanaTPG").withDate(7, 5);
        this.add("CharJang").withDate(7, 8);
        this.add("Star_dark").withDate(7, 10);
        this.add("jixin").withDate(7, 12);
        this.add("Godyum").withDate(7, 16);
        this.add("于小黑想重开").withDate(7, 17);
        this.add("海曦").withDate(7, 21);
        this.add("假人偶咯").withDate(7, 24);
        this.add("ALK阿狸控").withDate(7, 25);
        this.add("牧子鱼").withDate(7, 25);
        this.add("想摆烂的卡洛诺斯").withDate(7, 26);
        this.add("while1cry").withDate(7, 31);
        this.add("xu_zai").withDate(7, 31);
        this.add("孤蔑冰空").withDate(8, 3);
        this.add("dnc").withDate(8, 8);
        this.add("Miraitowa").withDate(8, 8);
        this.add("寒炎五月").withDate(8, 8);
        this.add("BaiZe-白泽").withDate(8, 8);
        this.add("小贤").withDate(8, 11);
        this.add("Starfrost").withDate(8, 11);
        this.add("OMGDays", "...").withDate(8, 12);
        this.add("瓦合-SAME").withDate(8, 13);
        this.add("YMRSL").withDate(8, 14);
        this.add("zhoubanxian233").withDate(8, 16);
        this.add("瓶盖PING", "https://space.bilibili.com/79043581").withDate(8, 19);
        this.add("Amel_Lam献督").withDate(8, 21);
        this.add("阿秩rank").withDate(8, 29);
        this.add("卿冬与千").withDate(8, 29);
        this.add("SqrtPi_").withDate(8, 30);
        this.add("小啊雨大王").withDate(9, 9);
        this.add("FoFTG", "https://space.bilibili.com/26032219/", "...").withDate(9, 9);
        this.add("WHYHW2297").withDate(9, 9);
        this.add("tianmen").withDate(10, 4);
        this.add("寄水晶").withDate(10, 8);
        this.add("Easecation").withDate(11, 8);
        this.add("The_Crispy", "https://space.bilibili.com/3546733667682452").withDate(12, 1);
        this.add("九思").withDate(12, 16);
        this.add("因为42").withDate(12, 23);
        this.add("吾乃曲奇PigeonCookie").withDate(12, 26);
        this.add("Raccoon Spoon").withDate(12, 30);
        this.add("李来福AnlBE").withDate(2025, 1, 6);
        this.add("酋长_chief").withDate(2025, 1, 14);
        this.add("Wi2ter").withDate(2025, 1, 21);
        this.add("Wi2ter").withDate(2025, 1, 21);
        this.add("清歌栀耳").withDate(2025, 1, 22);
        this.add("臻选黄昏蛋").withDate(2025, 1, 29);
        this.add("Nootviri").withDate(2025, 1, 31);
        this.add("shuai123").withDate(2025, 2, 9);
        this.add("李世言", "...").withDate(2025, 2, 10);

        /* Patreon */
        this.add("terbin", "https://www.youtube.com/channel/UCD4X2slLdD_WJxlW03JPVQQ", "...").withDate(2, 23);
        this.add("Kirkus").withDate(2, 23);
        this.add("Tanner Walterman").withDate(2, 23);
        this.add("Rheed The Legend", "https://www.youtube.com/@rheedcraft").withDate(2, 23);
        this.add("CraZzZy Boy", "...").withDate(2, 23);
        this.add("fastvincent1").withDate(2, 23);
        this.add("Mor14").withDate(2, 23);
        this.add("B13 Pictures").withDate(2, 23);
        this.add("Satorik").withDate(2, 23);
        this.add("SkedgyEdgy", "https://www.youtube.com/skedgyedgy", "textures/banners/skedgyedgy.png").withDate(2, 23);
        this.add("MrBurNik", "https://www.youtube.com/channel/UCnmttzfQHsBw0GefMToNwpA").withDate(2, 23);
        this.add("Joziah3", "https://www.youtube.com/channel/UC8cnHS3Ub_EEzuaESD8E-ow").withDate(2, 24);
        this.add("CreeperGoldMC").withDate(2, 24);
        this.add("Roma on YouTube").withDate(2, 24);
        this.add("Kazuma").withDate(2, 24);
        this.add("JesseMauve", "https://www.youtube.com/@JesseMauve/videos").withDate(2, 24);
        this.add("Gugli").withDate(2, 24);
        this.add("theFallEquinox").withDate(2, 24);
        this.add("Pixe_GUM").withDate(2, 25);
        this.add("RunnyHero").withDate(2, 25);
        this.add("Chunk7", "https://space.bilibili.com/2840677", "textures/banners/chunk7.png").withDate(2, 25);
        this.add("Kludge", "https://www.youtube.com/@kluudge").withDate(2, 25);
        this.add("seb024YT").withDate(2, 27);
        this.add("良辰 薛").withDate(2, 27);
        this.add("PracticeTyping").withDate(2, 27);
        this.add("GEVids", "https://www.youtube.com/c/GEVids", "...").withDate(2, 27);
        this.add("IPhonelover XD").withDate(2, 28);
        this.add("Klalorathy", "...").withDate(2, 29);
        this.add("technodwarf", "https://www.youtube.com/@technodwarf").withDate(2, 29);
        this.add("Linkyam9").withDate(3, 1);
        this.add("Hermeticlock", "https://www.youtube.com/channel/UCbeyfcexbuO7NalTJn9akTw").withDate(3, 1);
        this.add("ぶろう").withDate(3, 1);
        this.add("Naos", "...").withDate(3, 1);
        this.add("Pexiaus").withDate(3, 1);
        this.add("The Anime Protagonist", "https://www.youtube.com/@DuhAnimeProtagonist/featured").withDate(3, 1);
        this.add("wangyupu").withDate(3, 2);
        this.add("Wone_J", "https://space.bilibili.com/13505331").withDate(3, 2);
        this.add("资 云").withDate(3, 4);
        this.add("Michael Creeper_", "https://twitter.com/MichaelCreeper", "textures/banners/michaelcreeper_.png").withDate(3, 5);
        this.add("Sundown Story").withDate(3, 5);
        this.add("NotSafe", "https://www.youtube.com/@NotSafe/videos", "textures/banners/notsafe.png").withDate(3, 8);
        this.add("sniffierpond").withDate(3, 10);
        this.add("Geno").withDate(3, 12);
        this.add("Frosty1239869").withDate(3, 13);
        this.add("LunazStudios", "https://twitter.com/LunazStudios").withDate(3, 14);
        this.add("Bourner").withDate(3, 16);
        this.add("N. Popovich").withDate(3, 18);
        this.add("InmoNum").withDate(3, 23);
        this.add("akirashio").withDate(3, 24);
        this.add("StarcClans").withDate(3, 24);
        this.add("Jakinho", "https://www.youtube.com/@Jakinho", "textures/banners/jakinho.png").withDate(3, 24);
        this.add("Pimpochka Games", "https://pimpochka.games/", "textures/banners/pimpochka_games.png").withDate(3, 25);
        this.add("Nioum").withDate(3, 27);
        this.add("D. Janvier").withDate(3, 27);
        this.add("FinalBlock Studios", "https://finalblockstudios.com/", "textures/banners/finalblock_studios.png").withDate(4, 1);
        this.add("FunkyFight", "https://www.youtube.com/@FunkyFight", "textures/banners/funkyfight.png").withDate(4, 2);
        this.add("FaithStudios").withDate(4, 2);
        this.add("Ivan Dmitriyev").withDate(4, 4);
        this.add("Schneider", "https://www.youtube.com/@SchneiderGamesOFC").withDate(4, 5);
        this.add("FaithStudios").withDate(4, 5);
        this.add("Nightie").withDate(4, 10);
        this.add("P. C. Thái", "...").withDate(4, 11);
        this.add("Ylizioo").withDate(4, 12);
        this.add("Jekipung").withDate(4, 12);
        this.add("Exotic Domo Sniper", "...").withDate(4, 12);
        this.add("Sir Sean").withDate(4, 12);
        this.add("JohnJoyBillion").withDate(4, 13);
        this.add("이TV 달").withDate(4, 13);
        this.add("Terry Bleuh", "https://www.youtube.com/@TerryBleuh/featured").withDate(4, 15);
        this.add("Gebe").withDate(4, 15);
        this.add("2TK_craft").withDate(4, 17);
        this.add("poplistic").withDate(4, 17);
        this.add("mrPixBro").withDate(4, 18);
        this.add("Remy G.", "...").withDate(4, 20);
        this.add("LuckyPickle", "https://www.youtube.com/@luckypicklex").withDate(4, 20);
        this.add("Hermiticlock", "https://www.youtube.com/channel/UCbeyfcexbuO7NalTJn9akTw").withDate(4, 20);
        this.add("Positive Vibes Only").withDate(4, 21);
        this.add("Little.Froggy").withDate(4, 21);
        this.add("AND_010").withDate(4, 21);
        this.add("jDeV7").withDate(4, 21);
        this.add("BBPC").withDate(4, 21);
        this.add("NEXT ENTERTAINMENT STUDIOS").withDate(4, 21);
        this.add("Jivalon").withDate(4, 22);
        this.add("Croc").withDate(4, 22);
        this.add("P1asmaDev", "...").withDate(4, 23);
        this.add("SergiDPlay", "https://www.youtube.com/channel/UCt9X0GcCz7s1kjV33VEqEcA").withDate(4, 23);
        this.add("sollymcwolly").withDate(4, 23);
        this.add("Kaguno").withDate(4, 25);
        this.add("Si-ko").withDate(4, 25);
        this.add("LuanLGH").withDate(4, 26);
        this.add("TristanNLD", "https://www.youtube.com/channel/UCIx2ao8z9bryI7rvIl5Yszg").withDate(4, 26);
        this.add("CheesyKirah").withDate(4, 26);
        this.add("szoki").withDate(4, 26);
        this.add("Austin").withDate(4, 26);
        this.add("Furious Clash", "...").withDate(4, 26);
        this.add("Shawn H.").withDate(4, 26);
        this.add("LittleLightz").withDate(4, 26);
        this.add("Slightly Insulting").withDate(4, 26);
        this.add("GarzyField", "https://www.youtube.com/@GarzyField").withDate(4, 26);
        this.add("Gabriel Dametto").withDate(4, 26);
        this.add("Ninja2die").withDate(4, 26);
        this.add("Anniken").withDate(4, 26);
        this.add("Dysthy").withDate(4, 26);
        this.add("DonFuria").withDate(4, 26);
        this.add("Pedro M.").withDate(4, 26);
        this.add("Voxel").withDate(4, 26);
        this.add("Chicky").withDate(4, 27);
        this.add("고대고래 xOz6").withDate(4, 27);
        this.add("Monanatime").withDate(4, 27);
        this.add("LFM").withDate(4, 27);
        this.add("PoopSolider").withDate(4, 27);
        this.add("TheGamerstree").withDate(4, 27);
        this.add("Юрий М.").withDate(4, 27);
        this.add("Freddy Liu").withDate(4, 27);
        this.add("깃발 김").withDate(4, 27);
        this.add("Julien R.").withDate(4, 27);
        this.add("Tuguim").withDate(4, 27);
        this.add("Veasper").withDate(4, 27);
        this.add("Blue spaget").withDate(4, 27);
        this.add("LittleFilms").withDate(4, 27);
        this.add("Haxies").withDate(4, 27);
        this.add("alvaro piña 2036").withDate(4, 27);
        this.add("German M.").withDate(4, 28);
        this.add("Augusto").withDate(4, 28);
        this.add("ElMrFloppa").withDate(4, 28);
        this.add("Moretingz").withDate(4, 28);
        this.add("MCPA Team").withDate(4, 28);
        this.add("sanGGara 11").withDate(4, 28);
        this.add("Swiftbit").withDate(4, 28);
        this.add("XandarHD").withDate(4, 28);
        this.add("AlexiosTheSixth").withDate(4, 28);
        this.add("Colino").withDate(4, 28);
        this.add("Nekoma").withDate(4, 29);
        this.add("AhmedSEGA").withDate(4, 29);
        this.add("Sbriser").withDate(4, 29);
        this.add("Dominik J.").withDate(4, 29);
        this.add("Innova Creation").withDate(4, 30);
        this.add("Monkey Kev").withDate(4, 30);
        this.add("Francisco Sepulveda").withDate(4, 30);
        this.add("Nassou Oasis").withDate(4, 30);
        this.add("Tralla").withDate(4, 30);
        this.add("Punk Pink").withDate(4, 30);
        this.add("Bitzel").withDate(5, 1);
        this.add("Autruliem").withDate(5, 1);
        this.add("Miner's Cave").withDate(5, 1);
        this.add("PabeloNotEscobar").withDate(5, 1);
        this.add("Dilon Hoare").withDate(5, 1);
        this.add("BlueChicken 32").withDate(5, 1);
        this.add("James M.").withDate(5, 1);
        this.add("0xb7").withDate(5, 2);
        this.add("MiuxuE").withDate(5, 2);
        this.add("Juanes23").withDate(5, 2);
        this.add("yauhyeah").withDate(5, 2);
        this.add("long xiao").withDate(5, 2);
        this.add("1Frezzy").withDate(5, 2);
        this.add("Jeffin").withDate(5, 2);
        this.add("Tahyme").withDate(5, 2);
        this.add("MineCrafty").withDate(5, 3);
        this.add("TomyCresyler").withDate(5, 4);
        this.add("V0IDCreates").withDate(5, 4);
        this.add("MandyMiss").withDate(5, 5);
        this.add("Liam Floyd", "https://x.com/mistergriimm").withDate(5, 5);
        this.add("구름 고양").withDate(5, 5);
        this.add("Tafukoni").withDate(5, 5);
        this.add("FrostAngelWolf").withDate(5, 6);
        this.add("Intelligent Idiot").withDate(5, 6);
        this.add("ItsGlac").withDate(5, 6);
        this.add("Rexiipher").withDate(5, 6);
        // this.add("Hugo s.").withDate(5, 7);
        this.add("Blindedtrvlr").withDate(5, 7);
        this.add("zexticss").withDate(5, 7);
        this.add("AMVS Universe", "https://www.youtube.com/@AMVSUniverse1/featured", "textures/banners/amvs.png").withDate(5, 8);
        this.add("Odiei zim").withDate(5, 8);
        this.add("Kyttu").withDate(5, 8);
        this.add("minegamerr").withDate(5, 8);
        this.add("Miles M.").withDate(5, 8);
        this.add("Scooter", "https://twitter.com/ScotScooter", "textures/banners/scooter.png").withDate(5, 9);
        this.add("Silverx Productions").withDate(5, 9);
        this.add("【OMGDays】").withDate(5, 10);
        this.add("Hangert").withDate(5, 10);
        this.add("C4ptainF0xy").withDate(5, 11);
        this.add("Hfsiu F.").withDate(5, 11);
        this.add("inhisarlideliyakup").withDate(5, 11);
        this.add("KudoDerg").withDate(5, 11);
        this.add("EinfachJoey").withDate(5, 12);
        this.add("Santiago AAP").withDate(5, 12);
        this.add("Rüyaperest", "https://www.youtube.com/@Ruyaperest", "textures/banners/ruyaperest.png").withDate(5, 13);
        this.add("novaplays123").withDate(5, 14);
        this.add("WiserLake").withDate(5, 15);
        this.add("Flayming MC", "https://www.youtube.com/channel/UC3b8_VlQVXpu7e0MUPLHdBA", "textures/banners/flayming.png").withDate(5, 16);
        this.add("SteelChikorita").withDate(5, 16);
        this.add("Thiago Almeida de Souza").withDate(5, 17);
        this.add("Matthew B.").withDate(5, 17);
        this.add("LegalStudioz").withDate(5, 17);
        this.add("NovaDoesGaming").withDate(5, 17);
        this.add("Aaron").withDate(5, 18);
        this.add("Gorian cf").withDate(5, 18);
        this.add("RedstoneWizard08").withDate(5, 18);
        this.add("Adam").withDate(5, 19);
        this.add("MixinFlow").withDate(5, 19);
        this.add("Ben").withDate(5, 19);
        this.add("Matthew White").withDate(5, 19);
        this.add("Airb0ll").withDate(5, 19);
        this.add("CitrusWasHere").withDate(5, 20);
        this.add("Sam Su").withDate(5, 20);
        this.add("Aesthics").withDate(5, 20);
        this.add("FavreMySabre", "https://www.youtube.com/channel/UCE8AXzs4x8VDoC58JYppO2g").withDate(5, 20);
        this.add("Hunted", "...").withDate(5, 21);
        this.add("Berko Bey").withDate(5, 21);
        this.add("Dartsgame").withDate(5, 21);
        this.add(". 루").withDate(5, 22);
        this.add("Dima T.").withDate(5, 22);
        this.add("Kadukos").withDate(5, 22);
        this.add("Mattux").withDate(5, 22);
        this.add("Coriníon M.-L.").withDate(5, 23);
        this.add("Bobicraft").withDate(5, 23);
        this.add("Fogarty Fox").withDate(5, 24);
        this.add("MattNight").withDate(5, 25);
        this.add("akdong2003").withDate(5, 26);
        this.add("Misuya_XZ").withDate(5, 26);
        this.add("Metehan G.").withDate(5, 26);
        this.add("LogoJK").withDate(5, 26);
        this.add("Jacob G.").withDate(5, 27);
        this.add("Will M.").withDate(5, 28);
        this.add("KokunShorts").withDate(5, 28);
        this.add("Myshr00m").withDate(5, 28);
        this.add("Dark Cat").withDate(5, 29);
        this.add("Renardo").withDate(5, 30);
        this.add("RealMeal").withDate(5, 31);
        this.add("Twooearly").withDate(5, 31);
        this.add("alfajor").withDate(5, 31);
        this.add("Nguyễn Tiến T.").withDate(6, 1);
        this.add("El_Redstoniano").withDate(6, 1);
        this.add("ぴり").withDate(6, 2);
        this.add("Prezz").withDate(6, 2);
        this.add("Simon").withDate(6, 2);
        this.add("SystemLoading").withDate(6, 3);
        this.add("Many").withDate(6, 3);
        this.add("AresMC", "...").withDate(6, 3);
        this.add("G4BRIIEEL").withDate(6, 3);
        this.add("Astral").withDate(6, 4);
        this.add("Kuzyn Cyborg").withDate(6, 4);
        this.add("CharlyHorseman").withDate(6, 4);
        this.add("Karna").withDate(6, 5);
        this.add("craftgile").withDate(6, 8);
        this.add("Snamu").withDate(6, 8);
        this.add("FlameTFA").withDate(6, 9);
        this.add("StillSkittles", "https://youtube.com/@stillskittles?si=8p3aZL88VeZZwqhK").withDate(6, 9);
        this.add("eocx", "...").withDate(6, 10);
        this.add("Agnis_").withDate(6, 10);
        this.add("Evoken").withDate(6, 12);
        this.add("TheUncertainKing").withDate(6, 13);
        this.add("creeperz653").withDate(6, 13);
        this.add("KeiBoogie").withDate(6, 14);
        this.add("Mystievous").withDate(6, 14);
        this.add("The Veltins`s").withDate(6, 17);
        this.add("Karotti").withDate(6, 19);
        this.add("Josef Maslanyj").withDate(6, 19);
        this.add("Hugo Lovi").withDate(6, 19);
        this.add("EwLiyah").withDate(6, 20);
        this.add("ศุภวิชญ์ พ.").withDate(6, 21);
        this.add("jeremy").withDate(6, 23);
        this.add("Jet Hidden").withDate(6, 23);
        this.add("cdr").withDate(6, 25);
        this.add("Iago Manna").withDate(6, 25);
        this.add("Godricxs").withDate(6, 26);
        // this.add("Rusted_AK", "...").withDate(6, 26);
        this.add("LOKIOLR", "https://youtube.com/@lokiolr").withDate(6, 26);
        this.add("zenozz BTS", "...").withDate(6, 28);
        this.add("DraKhaos").withDate(7, 1);
        this.add("Neotrix").withDate(7, 2);
        this.add("Nederlander_Khan").withDate(7, 3);
        this.add("REHDM").withDate(7, 3);
        this.add("GoldenNooby").withDate(7, 4);
        this.add("wa tashi").withDate(7, 4);
        this.add("Hoàng H.").withDate(7, 7);
        this.add("Cube Clown").withDate(7, 7);
        this.add("Zeros").withDate(7, 8);
        this.add("panfontanna").withDate(7, 8);
        this.add("ViaTrip").withDate(7, 8);
        this.add("FlyZ3r").withDate(7, 9);
        this.add("Billicraft").withDate(7, 10);
        this.add("Game").withDate(7, 10);
        this.add("Sam E.").withDate(7, 11);
        this.add("ซี บีโอเอสเอส").withDate(7, 11);
        this.add("Movie Shitheads").withDate(7, 12);
        this.add("Luckman42").withDate(7, 13);
        this.add("CAKE!").withDate(7, 14);
        this.add("MENYX").withDate(7, 15);
        this.add("Filipfico").withDate(7, 15);
        this.add("Budder Productions").withDate(7, 16);
        this.add("Pink", "https://youtube.com/@pinkthegoober").withDate(7, 17);
        this.add("BenlikesSharks").withDate(7, 17);
        this.add("Custom").withDate(7, 17);
        this.add("Alex Gorcas").withDate(7, 19);
        this.add("PizzaStudios").withDate(7, 20);
        this.add("Ibrahim A.").withDate(7, 20);
        this.add("BrainCells").withDate(7, 20);
        this.add("Sebastian Ruditz").withDate(7, 20);
        this.add("Caméléon Gamer").withDate(7, 21);
        this.add("Mii").withDate(7, 22);
        this.add("TimesLooper").withDate(7, 23);
        this.add("Ez Ez").withDate(7, 23);
        this.add("Liam Vinokurov").withDate(7, 24);
        this.add("TooFfion").withDate(7, 25);
        this.add("Catolo FW").withDate(7, 26);
        this.add("José Caballero").withDate(7, 26);
        this.add("Biggerest").withDate(7, 26);
        this.add("Wonder Studios").withDate(7, 27);
        this.add("HibridNil").withDate(7, 27);
        this.add("CT Me").withDate(7, 27);
        this.add("Amsther").withDate(7, 27);
        this.add("Sammy_Boy_Br 123").withDate(7, 28);
        this.add("Tse Tin").withDate(7, 29);
        this.add("Minaduk1").withDate(7, 30);
        this.add("Riggih A.", "...").withDate(7, 30);
        this.add("T4ddyGamesBR", "https://www.youtube.com/@BUNGas99").withDate(7, 30);
        this.add("ChillinWithDylan", "https://www.youtube.com/channel/UCM8yL498_xlj-oOMAjM7CPA").withDate(7, 31);
        this.add("Shaw O.").withDate(8, 3);
        this.add("Furrosuti").withDate(8, 3);
        this.add("nerotvlive").withDate(8, 3);
        this.add("MST Masatu").withDate(8, 4);
        this.add("ToMiiX").withDate(8, 7);
        this.add("Neko").withDate(8, 8);
        this.add("Udjs Jdjd").withDate(8, 8);
        this.add("Joel A.").withDate(8, 9);
        this.add("Saint D.").withDate(8, 9);
        this.add("hyperboy 761").withDate(8, 10);
        this.add("ZeniStudios").withDate(8, 11);
        this.add("Marco D.", "...").withDate(8, 11);
        this.add("Snifferish", "https://www.youtube.com/@Snifferish").withDate(8, 12);
        this.add("DerEntspannte").withDate(8, 13);
        this.add("Dark Corners", "https://www.youtube.com/@DarkCornersTV").withDate(8, 14);
        this.add("Infy").withDate(8, 15);
        this.add("Problems YT").withDate(8, 21);
        this.add("SpyQu", "https://www.youtube.com/@SpyQu").withDate(8, 25);
        this.add("The Coastal Tavern").withDate(8, 26);
        this.add("Leo A.").withDate(9, 1);
        this.add("marlow").withDate(9, 14);
        this.add("Mr. Blaster").withDate(9, 15);
        this.add("Paresh Solanki").withDate(9, 21);
        this.add("BALOO").withDate(9, 22);
        this.add("NurDeko").withDate(9, 22);
        this.add("Hakan_Sef").withDate(9, 23);
        this.add("KiLAB").withDate(9, 23);
        this.add("Ferited").withDate(9, 24);
        this.add("MarioCraft31").withDate(9, 25);
        this.add("Donepi").withDate(9, 29);
        this.add("Exhaustes Yami", "https://lnk.bio/exhausted").withDate(10, 3);
        this.add("Checkpoint").withDate(10, 3);
        this.add("Miauzinha The Kitty").withDate(10, 6);
        this.add("Verpixelt").withDate(10, 6);
        this.add("Feytown").withDate(10, 6);
        this.add("wesley-PC").withDate(10, 7);
        this.add("Corujinh4").withDate(10, 7);
        this.add("hhharleyy").withDate(10, 8);
        this.add("Nala K.").withDate(10, 10);
        this.add("Hafidz J.").withDate(10, 14);
        this.add("Alemanni").withDate(10, 24);
        this.add("zeyxon 24").withDate(10, 27);
        this.add("fanku", "https://ytjobs.co/talent/profile/22147").withDate(10, 30);
        this.add("Ace").withDate(11, 1);
        this.add("Stalling Set").withDate(11, 2);
        this.add("Creative Studio").withDate(11, 3);
        this.add("Kevin K.").withDate(11, 7);
        this.add("Arctic Taco Gaming").withDate(11, 8);
        this.add("Addison Nichols").withDate(11, 9);
        this.add("Joll", "https://www.youtube.com/channel/UClcqpZhHYcoRADrYmaGqVZA").withDate(11, 11);
        this.add("AlGowzXD").withDate(11, 15);
        this.add("Sean").withDate(11, 19);
        this.add("Moon Light").withDate(12, 3);
        this.add("Gabriel Meister").withDate(12, 3);
        this.add("PasteleFaerie", "https://www.youtube.com/channel/UC44uOBI-7Kh5gCl3JJ_vDsw").withDate(12, 8);
        this.add("Sonic0810").withDate(12, 10);
        this.add("Michael Flowers").withDate(12, 12);
        this.add("RedNgt").withDate(12, 31);
        this.add("유튜브 댕댕이", "...").withDate(2025, 1, 8);
        this.add("Pizzaronee", "https://www.youtube.com/@pizzaroneee").withDate(2025, 1, 22);
        this.add("ณัฐวุฒิ ทวาแสน").withDate(2025, 1, 31);
        this.add("Kubilay Kaan A.").withDate(2025, 2, 3);
        this.add("Why Not").withDate(2025, 2, 3);
        this.add("DorikiTheSimp").withDate(2025, 2, 4);
        this.add("Mayjk").withDate(2025, 2, 5);
        this.add("Quackers Clone").withDate(2025, 2, 6);
        this.add("Jay R.").withDate(2025, 2, 6);
        this.add("Cujo").withDate(2025, 2, 6);
        this.add("SpookGaming").withDate(2025, 2, 7);
        this.add("ImHarry").withDate(2025, 2, 9);

        // Thank you very much for donation! 😊 Is $ is the name you want to be included in BBS mod?
        // Thank you very much for donation! 😊 Is $ is the name you want to be included in BBS mod? Also, you can provide a link to your social media account (like YouTube, Twitter, TikTok, etc.)

        /* Boosty */
        this.add("Clesten", "https://www.youtube.com/@clesten", "textures/banners/clesten.png").withDate(3, 6);
        this.add("MRkoteich").withDate(4, 27);
        this.add("Mait53").withDate(4, 27);
        this.add("osas.exe").withDate(4, 27);
        this.add("JhonParker").withDate(4, 27);
        this.add("Stylent", "...").withDate(4, 28);
        this.add("The Mine Pixel Cool Studio").withDate(4, 28);
        this.add("KIZRUM").withDate(4, 28);
        this.add("KrabovayPolochka").withDate(4, 28);
        this.add("ЦитРусня").withDate(4, 28);
        this.add("Emilianov").withDate(4, 28);
        this.add("FeRiN_Tiamilox").withDate(4, 28);
        this.add("LENb3").withDate(4, 28);
        this.add("crack_arab").withDate(4, 29);
        this.add("Babidgon24").withDate(4, 29);
        this.add("Skorvod").withDate(4, 29);
        this.add("Василий С.").withDate(4, 29);
        this.add("Sizomuni").withDate(4, 29);
        this.add("donquixotea").withDate(4, 29);
        this.add("Mudyi").withDate(4, 30);
        this.add("ellatuk").withDate(4, 30);
        this.add("BiNdi_").withDate(5, 1);
        this.add("Filliks&Line").withDate(5, 1);
        this.add("BCFuril").withDate(5, 1);
        this.add("Slippers_friend").withDate(5, 1);
        this.add("TheBendy").withDate(5, 1);
        this.add("Just Fect").withDate(5, 1);
        this.add("mr.ifu").withDate(5, 2);
        this.add("Тимобус 223").withDate(5, 3);
        this.add("Jabochca_Soviet").withDate(5, 5);
        this.add("Venya Play").withDate(5, 5);
        this.add("K.I.N - Prod.").withDate(5, 6);
        this.add("KlashRaick").withDate(5, 7);
        this.add("Lastochkin").withDate(5, 7);
        this.add("RayMelhor").withDate(5, 8);
        this.add("Andre").withDate(5, 8);
        this.add("_KvardSeries_").withDate(5, 9);
        this.add("paynqqwr").withDate(5, 9);
        this.add("_K0ks1k").withDate(5, 10);
        this.add("Dimak Lapkin", "https://www.youtube.com/channel/UCOomCTimgx20zd4Xynuv9sQ").withDate(5, 10);
        this.add("XlebkinS").withDate(5, 12);
        this.add("ZombieGamerz").withDate(5, 16);
        this.add("momfc").withDate(5, 19);
        this.add("TheMANTLE").withDate(5, 20);
        this.add("GensaMine").withDate(5, 21);
        this.add("-AVACH-").withDate(5, 22);
        this.add("Найтингейл", "https://www.youtube.com/@19gale").withDate(5, 22);
        // this.add("b0b0b0").withDate(5, 23); This guy doesn't deserve a mention, because of the leak
        this.add("Zing").withDate(5, 23);
        this.add("yurafakel").withDate(5, 28);
        this.add("GooseTeam").withDate(5, 30);
        this.add("LarsCraftAnimation").withDate(5, 30);
        this.add("Goose Team").withDate(5, 30);
        this.add("Nabemo53").withDate(5, 31);
        this.add("BeGereshka").withDate(6, 3);
        this.add("MyStoryProd").withDate(6, 4);
        this.add("zeldon").withDate(6, 7);
        this.add("Ahmed SEGA").withDate(6, 7);
        this.add("IWaithI").withDate(6, 7);
        this.add("xzeldon").withDate(6, 7);
        this.add("FinalFrame").withDate(6, 10);
        this.add("Komentator").withDate(6, 10);
        this.add("Danlend_lol").withDate(6, 11);
        this.add("DOK").withDate(6, 14);
        this.add("Сергей Ш.").withDate(6, 17);
        this.add("Leon").withDate(6, 18);
        this.add("melow").withDate(6, 23);
        this.add("fenny013").withDate(6, 23);
        this.add("onleew").withDate(6, 25);
        this.add("Hellbug_U").withDate(6, 29);
        this.add("Krimor").withDate(6, 30);
        this.add("Murlovich").withDate(7, 3);
        this.add("VladisCrafter").withDate(7, 5);
        this.add("Никита П.").withDate(7, 12);
        this.add("DimaStad").withDate(7, 14);
        this.add("RAMZES141").withDate(7, 14);
        this.add("wolfifurr").withDate(7, 15);
        this.add("QZero").withDate(7, 16);
        this.add("4ePHiT").withDate(7, 17);
        this.add("gammuk").withDate(7, 17);
        this.add("EsoKuro").withDate(7, 18);
        this.add("Allorific").withDate(7, 19);
        this.add("Enotiy").withDate(7, 26);
        this.add("Library Keeper").withDate(7, 26);
        this.add("dofimus").withDate(8, 1);
        this.add("Дмитрий М.").withDate(8, 3);
        this.add("Shkarkusha").withDate(8, 4);
        this.add("korupey").withDate(8, 8);
        this.add("Hosti1338").withDate(8, 29);
        this.add("Mel1x").withDate(9, 5);
        this.add("Eda Hari").withDate(9, 5);
        this.add("CTU4").withDate(9, 5);
        this.add("Solov").withDate(10, 10);
        this.add("dadadaeo").withDate(10, 19);
        this.add("_Nerds_").withDate(10, 20);
        this.add("Metla").withDate(10, 29);
        this.add("lizuun").withDate(11, 4);
        this.add("Mylozh").withDate(11, 7);
        this.add("perdibay").withDate(11, 28);
        this.add("mrmax").withDate(12, 3);
        this.add("Dranick").withDate(12, 24);
        this.add("Lu_t1k").withDate(12, 24);
        this.add("Filin").withDate(12, 24);
        this.add("Agleepi", "https://www.youtube.com/@agleepi", "...").withDate(2025, 1, 20);
        this.add("AGGRESSIVE-COOVIR-21!").withDate(2025, 2, 10); /* <3 */
        this.add("osmiq", "https://twitter.com/osmiq0", "textures/banners/osmiqtop1modeler.png").withDate(2025, 2, 19); /* <3 */

        /* Custom */
        this.add("Hrymka", "...", "textures/banners/hrymka.png").withDate(3, 6);
        this.add("Rasty", "https://www.youtube.com/@RastyStudio").withDate(3, 6);
        this.add("Afegor (Alyokhin Dmitrii)", "https://www.youtube.com/@Afegor", "textures/banners/afegor.png").withDate(4, 8);
        this.add("ZoGa", "...", "textures/banners/zogatop1animator.png").withDate(4, 22); /* <3 */
        this.add("qualet", "https://www.youtube.com/@qualet", "textures/banners/QUALET_QUALET_QUALET_QUALET_QUALET_QUALET_QUALET_QUALET_QUALET_QUALET.png").withDate(2025, 2, 3); /* <3 */
        this.add("McHorse", "https://www.youtube.com/channel/UCSLuDXxxql4EVK_Ktd6PNbw", "textures/banners/mchorse.png");

        int afdian = 5;
        int patreon = 0;
        int total = afdian + patreon;

        this.add("And " + total + " others...", "...");

        afdian = 16;
        patreon = 2;
        total = afdian + patreon;

        this.add("And " + total + " others...");
    }

    private Supporter add(String name)
    {
        return this.add(name, "");
    }

    private Supporter add(String name, String link)
    {
        return this.add(name, link, (Link) null);
    }

    private Supporter add(String name, String link, String banner)
    {
        return this.add(name, link, Link.create(banner));
    }

    private Supporter add(String name, String link, Link banner)
    {
        Supporter supporter = new Supporter(name, link, banner);

        this.supporters.add(supporter);

        return supporter;
    }

    public List<Supporter> getBBSEarlyAccessSupporters()
    {
        return this.supporters.stream().filter(Supporter::hasOnlyName).sorted(Comparator.comparing((a) -> a.date)).collect(Collectors.toList());
    }

    public List<Supporter> getSuperSupporters()
    {
        return this.supporters.stream().filter(Supporter::hasNoBanner).sorted(Comparator.comparing((a) -> a.date)).collect(Collectors.toList());
    }

    public List<Supporter> getCCSupporters()
    {
        return this.supporters.stream().filter(Supporter::hasBanner).sorted(Comparator.comparing((a) -> a.date)).collect(Collectors.toList());
    }
}